"""movies table

Revision ID: 8c2ae6c6498c
Revises: 
Create Date: 2021-01-05 11:56:17.689389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c2ae6c6498c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("original_title", sa.String(length=150), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("release", sa.String(length=30), nullable=True),
        sa.Column("storyline", sa.Text(), nullable=True),
        sa.Column("stars", sa.String(length=100), nullable=True),
        sa.Column("creator", sa.String(length=50), nullable=True),
        sa.Column("genres", sa.String(length=150), nullable=True),
        sa.Column("plot_keywords", sa.String(length=150), nullable=True),
        sa.Column("certificate", sa.String(length=10), nullable=True),
        sa.Column("movie_title", sa.String(length=150), nullable=True),
        sa.Column("title_year", sa.String(length=5), nullable=True),
        sa.Column("imdb_score", sa.String(length=4), nullable=True),
        sa.Column("number_ratings", sa.String(length=20), nullable=True),
        sa.Column("director", sa.String(length=50), nullable=True),
        sa.Column("writer", sa.String(length=50), nullable=True),
        sa.Column("episode_count", sa.String(length=15), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("budget", sa.Integer(), nullable=True),
        sa.Column("cum_worldwide_gross", sa.Integer(), nullable=True),
        sa.Column("poster", sa.String(length=250), nullable=True),
        sa.Column("big_poster", sa.String(length=250), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("index"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies")
    # ### end Alembic commands ###
